stages:
  feature:
    cmd: python main.py --stage feature_pipeline
    deps:
      - src/Condition2Cure/pipeline/feature_pipeline.py
      - src/Condition2Cure/config/data_config.py
      - src/Condition2Cure/config/config.yaml
      - src/Condition2Cure/config/params.yaml
      - src/Condition2Cure/config/schema.yaml
    
    outs:
      - artifacts/data_ingestion
      - artifacts/data_validation/status.json
      - artifacts/data_cleaning/cleaned.csv
      - artifacts/feature_engineering/vectorizer.pkl
      - artifacts/feature_engineering/svd.pkl
      - artifacts/feature_engineering/label_encoder.pkl


  model:
    cmd: python main.py --stage model_pipeline
    deps:
      - src/Condition2Cure/pipeline/model_pipeline.py
      - src/Condition2Cure/config/model_config.py
      - src/Condition2Cure/config/config.yaml
      - src/Condition2Cure/config/params.yaml
      - src/Condition2Cure/config/schema.yaml
    
    outs:
      - artifacts/model_training/model.joblib
      - artifacts/model_evaluation/metrics.json
      - artifacts/model_evaluation/cm.png
