stages:
  data_ingestion:
    cmd: python main.py --stage data_ingestion
    deps:
      - src/Condition2Cure/pipeline/stage1_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion

  data_validation:
    cmd: python main.py --stage data_validation
    deps:
      - src/Condition2Cure/pipeline/stage2_validation.py
      - artifacts/data_ingestion/Drugs_Data.csv
      - config/schema.yaml
    outs:
      - artifacts/data_validation/status.json

  data_cleaning:
    cmd: python main.py --stage data_cleaning
    deps:
      - src/Condition2Cure/pipeline/stage3_cleaning.py
      - artifacts/data_ingestion/Drugs_Data.csv
    outs:
      - artifacts/data_cleaning/cleaned.csv

  data_transformation:
    cmd: python main.py --stage data_transformation
    deps:
      - src/Condition2Cure/pipeline/stage4_transformation.py
      - artifacts/data_cleaning/cleaned.csv
      - config/params.yaml
    outs:
      - artifacts/feature_engineering/X.npy
      - artifacts/feature_engineering/y.npy
      - artifacts/feature_engineering/vectorizer.pkl
      - artifacts/feature_engineering/svd.pkl
      - artifacts/feature_engineering/label_encoder.pkl

  model_training:
    cmd: python main.py --stage model_training
    deps:
      - src/Condition2Cure/pipeline/stage5_training.py
      - artifacts/feature_engineering/X.npy
      - artifacts/feature_engineering/y.npy
      - config/params.yaml
    outs:
      - artifacts/model_training/model.joblib
      - artifacts/model_training/best_model_info.json

  model_evaluation:
    cmd: python main.py --stage model_evaluation
    deps:
      - src/Condition2Cure/pipeline/stage6_evaluation.py
      - artifacts/feature_engineering/X.npy
      - artifacts/feature_engineering/y.npy
      - artifacts/model_training/model.joblib
      - artifacts/feature_engineering/label_encoder.pkl
    outs:
      - artifacts/model_evaluation/metrics.json
      - artifacts/model_evaluation/cm.png

  model_registry:
    cmd: python main.py --stage model_registry
    deps:
      - src/Condition2Cure/pipeline/stage7_registry.py
      - artifacts/model_evaluation/metrics.json
    outs: []
