stages:
  ingestion:
    cmd: python -m Condition2Cure.components.data_ingestion
    deps:
      - src/Condition2Cure/components/data_ingestion.py
      - src/Condition2Cure/config.py
    outs:
      - artifacts/data_ingestion

  validation:
    cmd: python -m Condition2Cure.components.data_validation
    deps:
      - src/Condition2Cure/components/data_validation.py
      - src/Condition2Cure/config.py
      - artifacts/data_ingestion/Drugs_Data.csv
    outs:
      - artifacts/data_validation/status.json

  cleaning:
    cmd: python -m Condition2Cure.components.data_cleaning
    deps:
      - src/Condition2Cure/components/data_cleaning.py
      - src/Condition2Cure/config.py
      - src/Condition2Cure/utils/nlp_utils.py
      - artifacts/data_ingestion/Drugs_Data.csv
      - artifacts/data_validation/status.json
    outs:
      - artifacts/data_cleaning/cleaned.csv

  transformation:
    cmd: python -m Condition2Cure.components.data_transformation
    deps:
      - src/Condition2Cure/components/data_transformation.py
      - src/Condition2Cure/config.py
      - src/Condition2Cure/utils/nlp_utils.py
      - artifacts/data_cleaning/cleaned.csv
    outs:
      - artifacts/features/X_train.npy
      - artifacts/features/y_train.npy
      - artifacts/features/X_test.npy
      - artifacts/features/y_test.npy
      - artifacts/features/label_encoder.pkl

  training:
    cmd: python -m Condition2Cure.components.model_training
    deps:
      - src/Condition2Cure/components/model_training.py
      - src/Condition2Cure/config.py
      - src/Condition2Cure/utils/helpers.py
      - artifacts/features/X_train.npy
      - artifacts/features/y_train.npy
    outs:
      - artifacts/model/model.joblib
      - artifacts/model/training_info.json

  evaluation:
    cmd: python -m Condition2Cure.components.model_evaluation
    deps:
      - src/Condition2Cure/components/model_evaluation.py
      - src/Condition2Cure/config.py
      - src/Condition2Cure/utils/helpers.py
      - artifacts/features/X_test.npy
      - artifacts/features/y_test.npy
      - artifacts/features/label_encoder.pkl
      - artifacts/model/model.joblib
    outs:
      - artifacts/model/confusion_matrix.png
    metrics:
      - artifacts/model/metrics.json:
          cache: false
