artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_id: 10dmW5TSCk91lukqWcAeBSt9pjjv-xaFW
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Drugs_Data.csv
  status_file: artifacts/data_validation/status.json

data_cleaning:
  root_dir: artifacts/data_cleaning
  data_path: artifacts/data_ingestion/Drugs_Data.csv
  cleaned_data_path: artifacts/data_cleaning/cleaned.csv

feature_engineering:
  root_dir: artifacts/feature_engineering
  cleaned_data_path: artifacts/data_cleaning/cleaned.csv
  vectorizer_path: artifacts/feature_engineering/vectorizer.pkl
  svd_path: artifacts/feature_engineering/svd.pkl
  features_path: artifacts/feature_engineering/X.npy
  labels_path: artifacts/feature_engineering/y.npy
  label_encoder_path: artifacts/feature_engineering/label_encoder.pkl


model_training:
  root_dir: artifacts/model_training
  features_path: artifacts/feature_engineering/X.npy
  labels_path: artifacts/feature_engineering/y.npy
  model_path: artifacts/model_training/model.joblib


model_evaluation:
  root_dir: artifacts/model_evaluation
  features_path: artifacts/feature_engineering/X.npy
  labels_path: artifacts/feature_engineering/y.npy
  model_path: artifacts/model_training/model.joblib
  label_encoder_path: artifacts/feature_engineering/label_encoder.pkl
  metrics_path: artifacts/model_evaluation/metrics.json
  cm_path: artifacts/model_evaluation/cm.png


model_registry:
  model_name: Condition2CureModel
  metric_path: artifacts/model_evaluation/metrics.json
  metric_key: f1_weighted

monitoring:
  reference_data: artifacts/data_cleaning/cleaned.csv
  current_data: artifacts/data_cleaning/cleaned.csv
  output_dir: artifacts/monitoring
  